# Site settings
title: pusi77 # site title
description: >- # site description
  pusi77 personal site.
lang: en-US # default lang
timezone: Europe/Rome # set your timezone
repo: https://github.com/pusi77/pusi77.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Andrea Pusineri # author name
  bio: >- # tell to the world
    Computer engineering student, probably studying something that won't be in the next exam.
    <br>Check my <a href="https://github.com/pusi77" target="_blank" rel="noopener">github</a>.
  username: pusi77 # general username
  github: pusi77 # github username
  email: andrea.pusineri@universitadipavia.it # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://pusi77.github.io/" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: page
      comments: false

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
  - README.md

# Plugins
plugins:
  - jekyll-sitemap